export const restaurants = [
  {
    name: 'Rose Garden Restaurant',
    description:
      'A cozy place serving delicious burgers, pizzas, hot dogs, and biryanis.',
    items: [
      {
        name: 'Chicken Tikka Burger',
        category: {name: 'Burger'},
        price: 120,
        description: 'A juicy burger with grilled chicken tikka.',
      },
      {
        name: 'Cheese Burger',
        category: {name: 'Burger'},
        price: 100,
        description: 'A classic cheeseburger with melted cheese.',
      },
      {
        name: 'Classic Hot Dog',
        category: {name: 'Hot Dog'},
        price: 80,
        description: 'A simple hot dog with savory toppings.',
      },
      {
        name: 'Veggie Pizza',
        category: {name: 'Pizza'},
        price: 150,
        description: 'A pizza topped with fresh vegetables.',
      },
      {
        name: 'Chocolate Cake',
        category: {name: 'Cake and Desserts'},
        price: 90,
        description: 'A rich and moist chocolate cake.',
      },
      {
        name: 'Pepperoni Pizza',
        category: {name: 'Pizza'},
        price: 180,
        description: 'A pizza loaded with spicy pepperoni.',
      },
      {
        name: 'Chicken Sausage Hot Dog',
        category: {name: 'Hot Dog'},
        price: 110,
        description: 'Hot dog with chicken sausage and relish.',
      },
      {
        name: 'Paneer Pizza',
        category: {name: 'Pizza'},
        price: 160,
        description: 'A pizza with paneer and aromatic spices.',
      },
      {
        name: 'Black Forest Cake',
        category: {name: 'Cake and Desserts'},
        price: 110,
        description: 'A classic Black Forest cake with cherries.',
      },
      {
        name: 'Mutton Biryani',
        category: {name: 'Biryani'},
        price: 250,
        description: 'A flavorful biryani made with tender mutton.',
      },
      {
        name: 'Hyderabadi Chicken Biryani',
        category: {name: 'Biryani'},
        price: 230,
        description: 'Fragrant rice mixed with succulent chicken.',
      },
      {
        name: 'Spicy BBQ Hot Dog',
        category: {name: 'Hot Dog'},
        price: 120,
        description: 'Hot dog topped with spicy BBQ sauce.',
      },
    ],
    rating: 4.7,
    deliveryCharge: 0,
    deliveryTime: 20,
  },
  {
    name: 'Spice Heaven',
    description:
      'A spicy haven for biryani lovers and those who enjoy bold flavors.',
    items: [
      {
        name: 'Hyderabadi Biryani',
        category: {name: 'Biryani'},
        price: 230,
        description: 'Classic Hyderabadi biryani with rich spices.',
      },
      {
        name: 'Chicken Biryani',
        category: {name: 'Biryani'},
        price: 210,
        description: 'A chicken biryani with traditional flavors.',
      },
      {
        name: 'Veggie Pizza',
        category: {name: 'Pizza'},
        price: 160,
        description: 'A pizza with an assortment of fresh vegetables.',
      },
      {
        name: 'Double Cheeseburger',
        category: {name: 'Burger'},
        price: 180,
        description: 'Two layers of cheese and a juicy patty.',
      },
      {
        name: 'Vanilla Cake',
        category: {name: 'Cake and Desserts'},
        price: 85,
        description: 'A light and fluffy vanilla cake.',
      },
      {
        name: 'Chicken Nuggets Burger',
        category: {name: 'Burger'},
        price: 130,
        description: 'Crispy chicken nuggets in a soft burger bun.',
      },
      {
        name: 'Spicy Hot Dog',
        category: {name: 'Hot Dog'},
        price: 110,
        description: 'A spicy hot dog with a kick of jalapenos.',
      },
      {
        name: 'Paneer Butter Masala Pizza',
        category: {name: 'Pizza'},
        price: 180,
        description: 'Pizza with rich paneer butter masala topping.',
      },
      {
        name: 'Jumbo Hot Dog',
        category: {name: 'Hot Dog'},
        price: 140,
        description: 'A massive hot dog with extra toppings.',
      },
      {
        name: 'Red Velvet Cake',
        category: {name: 'Cake and Desserts'},
        price: 120,
        description: 'A rich and velvety red velvet cake.',
      },
      {
        name: 'Mutton Seekh Kebab Biryani',
        category: {name: 'Biryani'},
        price: 270,
        description: 'Biryani paired with tender mutton seekh kebabs.',
      },
      {
        name: 'Garlic Sausage Hot Dog',
        category: {name: 'Hot Dog'},
        price: 130,
        description: 'Hot dog with a smoky garlic sausage.',
      },
      {
        name: 'Triple Cheese Burger',
        category: {name: 'Burger'},
        price: 220,
        description: 'A cheese lover’s dream with three types of cheese.',
      },
    ],
    rating: 4.5,
    deliveryCharge: 20,
    deliveryTime: 25,
  },
  {
    name: 'Gourmet Bites',
    description: 'A gourmet experience with a range of exquisite dishes.',
    items: [
      {
        name: 'Pepperoni Pizza',
        category: {name: 'Pizza'},
        price: 170,
        description: 'Spicy pepperoni slices on a cheesy pizza.',
      },
      {
        name: 'Mutton Biryani',
        category: {name: 'Biryani'},
        price: 250,
        description: 'A savory mutton biryani with aromatic spices.',
      },
      {
        name: 'Strawberry Cake',
        category: {name: 'Cake and Desserts'},
        price: 95,
        description: 'A fruity and creamy strawberry cake.',
      },
      {
        name: 'Grilled Chicken Hot Dog',
        category: {name: 'Hot Dog'},
        price: 140,
        description: 'Grilled chicken in a hot dog bun with sauces.',
      },
      {
        name: 'BBQ Chicken Pizza',
        category: {name: 'Pizza'},
        price: 200,
        description: 'BBQ chicken with smoky flavors on pizza.',
      },
      {
        name: 'Veg Supreme Pizza',
        category: {name: 'Pizza'},
        price: 160,
        description: 'A pizza filled with a variety of veggies.',
      },
      {
        name: 'Paneer Tikka Biryani',
        category: {name: 'Biryani'},
        price: 220,
        description: 'A vegetarian biryani made with paneer tikka.',
      },
      {
        name: 'Brownie Delight',
        category: {name: 'Cake and Desserts'},
        price: 110,
        description:
          'A rich chocolate brownie with a delightfully fudgy center.',
      },
      {
        name: 'Garlic Sausage Hot Dog',
        category: {name: 'Hot Dog'},
        price: 130,
        description: 'Sausage with garlic flavor, served in a soft bun.',
      },
      {
        name: 'Chicken Zinger Burger',
        category: {name: 'Burger'},
        price: 150,
        description: 'Crispy chicken patty with spicy seasoning.',
      },
      {
        name: 'Chocolate Lava Cake',
        category: {name: 'Cake and Desserts'},
        price: 130,
        description: 'A molten chocolate cake with a gooey center.',
      },
      {
        name: 'Hawaiian Pizza',
        category: {name: 'Pizza'},
        price: 180,
        description: 'Pizza topped with ham, pineapple, and cheese.',
      },
      {
        name: 'Spicy Mutton Burger',
        category: {name: 'Burger'},
        price: 160,
        description: 'Spicy mutton patty in a soft burger bun.',
      },
    ],
    rating: 4.8,
    deliveryCharge: 10,
    deliveryTime: 30,
  },
  {
    name: 'Flavors of India',
    description: 'Bringing the diverse flavors of India to your table.',
    items: [
      {
        name: 'Spicy Chicken Biryani',
        category: {name: 'Biryani'},
        price: 230,
        description: 'A spicy chicken biryani with rich Indian flavors.',
      },
      {
        name: 'Veggie Hot Dog',
        category: {name: 'Hot Dog'},
        price: 90,
        description: 'A healthy veggie hot dog with a flavorful sauce.',
      },
      {
        name: 'Margherita Pizza',
        category: {name: 'Pizza'},
        price: 140,
        description: 'A simple pizza with fresh basil and mozzarella.',
      },
      {
        name: 'Black Forest Cake',
        category: {name: 'Cake and Desserts'},
        price: 100,
        description:
          'A classic Black Forest cake with layers of chocolate and cherries.',
      },
      {
        name: 'Chicken Burger',
        category: {name: 'Burger'},
        price: 110,
        description: 'A delicious chicken burger with mayo and lettuce.',
      },
      {
        name: 'Butter Chicken Pizza',
        category: {name: 'Pizza'},
        price: 180,
        description: 'Pizza with creamy butter chicken topping.',
      },
      {
        name: 'Double Patty Burger',
        category: {name: 'Burger'},
        price: 160,
        description: 'A double patty burger with extra cheese.',
      },
      {
        name: 'Pineapple Pastry',
        category: {name: 'Cake and Desserts'},
        price: 85,
        description: 'A sweet pineapple pastry with a soft crust.',
      },
      {
        name: 'Kashmiri Mutton Biryani',
        category: {name: 'Biryani'},
        price: 270,
        description: 'Aromatic and rich Kashmiri-style mutton biryani.',
      },
      {
        name: 'Spicy Paneer Hot Dog',
        category: {name: 'Hot Dog'},
        price: 120,
        description: 'Hot dog with spicy paneer filling.',
      },
      {
        name: 'Cheese Garlic Bread',
        category: {name: 'Pizza'},
        price: 90,
        description: 'Cheesy garlic bread served with pizza.',
      },
      {
        name: 'Chicken Sausage Hot Dog',
        category: {name: 'Hot Dog'},
        price: 130,
        description: 'Hot dog with chicken sausage and tangy sauce.',
      },
      {
        name: 'Chicken Seekh Kebab Biryani',
        category: {name: 'Biryani'},
        price: 260,
        description: 'Biryani served with succulent chicken seekh kebabs.',
      },
    ],
    rating: 4.6,
    deliveryCharge: 25,
    deliveryTime: 35,
  },
  {
    name: 'Urban Grill',
    description:
      'A modern restaurant offering grilled delights and a variety of pizzas.',
    items: [
      {
        name: 'BBQ Chicken Pizza',
        category: {name: 'Pizza'},
        price: 180,
        description: 'Pizza topped with BBQ chicken and vegetables.',
      },
      {
        name: 'Brownie Delight',
        category: {name: 'Cake and Desserts'},
        price: 90,
        description: 'Warm brownie served with vanilla ice cream.',
      },
      {
        name: 'Chicken Kebab Biryani',
        category: {name: 'Biryani'},
        price: 250,
        description: 'Aromatic biryani with juicy chicken kebabs.',
      },
      {
        name: 'Spicy Hot Dog',
        category: {name: 'Hot Dog'},
        price: 130,
        description: 'A spicy hot dog with jalapenos and tangy sauce.',
      },
      {
        name: 'Tandoori Chicken Pizza',
        category: {name: 'Pizza'},
        price: 200,
        description: 'Pizza with tandoori chicken and a hint of spices.',
      },
    ],
    rating: 4.7,
    deliveryCharge: 25,
    deliveryTime: 20,
  },
  {
    name: 'Royal Biryani House',
    description:
      'Specializing in biryanis and pizzas, a true haven for biryani lovers.',
    items: [
      {
        name: 'Hyderabadi Mutton Biryani',
        category: {name: 'Biryani'},
        price: 270,
        description: 'Classic Hyderabadi mutton biryani with fragrant spices.',
      },
      {
        name: 'Chicken Biryani',
        category: {name: 'Biryani'},
        price: 240,
        description: 'Aromatic biryani with tender chicken pieces.',
      },
      {
        name: 'Paneer Butter Masala Pizza',
        category: {name: 'Pizza'},
        price: 190,
        description: 'Pizza with creamy paneer butter masala topping.',
      },
      {
        name: 'Garlic Breadsticks',
        category: {name: 'Pizza'},
        price: 80,
        description: 'Crunchy garlic breadsticks served with dip.',
      },
      {
        name: 'Chicken Seekh Biryani',
        category: {name: 'Biryani'},
        price: 250,
        description: 'Flavorful biryani with spicy chicken seekh kebabs.',
      },
    ],
    rating: 4.5,
    deliveryCharge: 20,
    deliveryTime: 30,
  },
  {
    name: 'Taste of Italy',
    description:
      'Authentic Italian dishes with a special focus on pizzas and pastas.',
    items: [
      {
        name: 'Margherita Pizza',
        category: {name: 'Pizza'},
        price: 150,
        description: 'Classic pizza topped with mozzarella and basil.',
      },
      {
        name: 'Chicken Alfredo Pizza',
        category: {name: 'Pizza'},
        price: 220,
        description: 'Pizza topped with creamy chicken Alfredo sauce.',
      },
      {
        name: 'Tiramisu Cake',
        category: {name: 'Cake and Desserts'},
        price: 120,
        description: 'Delicious Italian Tiramisu cake with coffee flavors.',
      },
      {
        name: 'Pasta Alfredo',
        category: {name: 'Burger'},
        price: 200,
        description: 'Rich and creamy Alfredo pasta.',
      },
      {
        name: 'Chicken Zinger Burger',
        category: {name: 'Burger'},
        price: 160,
        description: 'Crunchy chicken burger with spicy sauce.',
      },
    ],
    rating: 4.8,
    deliveryCharge: 10,
    deliveryTime: 25,
  },
  {
    name: 'Biryani Baithak',
    description:
      'A place where biryani reigns supreme with a variety of flavors.',
    items: [
      {
        name: 'Mutton Biryani',
        category: {name: 'Biryani'},
        price: 250,
        description: 'Spicy and flavorful mutton biryani.',
      },
      {
        name: 'Chicken Biryani',
        category: {name: 'Biryani'},
        price: 230,
        description: 'Aromatic chicken biryani with a blend of spices.',
      },
      {
        name: 'Spicy Veggie Pizza',
        category: {name: 'Pizza'},
        price: 150,
        description: 'Pizza topped with a variety of spicy vegetables.',
      },
      {
        name: 'Chocolate Cake',
        category: {name: 'Cake and Desserts'},
        price: 100,
        description: 'Rich chocolate cake with a moist texture.',
      },
      {
        name: 'Classic Hot Dog',
        category: {name: 'Hot Dog'},
        price: 100,
        description: 'Classic hot dog with mustard and ketchup.',
      },
    ],
    rating: 4.6,
    deliveryCharge: 15,
    deliveryTime: 20,
  },
  {
    name: 'Dessert & Grill',
    description: 'A perfect combination of grilled food and heavenly desserts.',
    items: [
      {
        name: 'BBQ Chicken Pizza',
        category: {name: 'Pizza'},
        price: 180,
        description: 'BBQ chicken with tangy sauce and cheese.',
      },
      {
        name: 'Veggie Burger',
        category: {name: 'Burger'},
        price: 120,
        description:
          'Vegetarian burger with fresh veggies and a flavorful sauce.',
      },
      {
        name: 'Apple Pie',
        category: {name: 'Cake and Desserts'},
        price: 110,
        description: 'Delicious apple pie with a flaky crust.',
      },
      {
        name: 'Hot Dog Supreme',
        category: {name: 'Hot Dog'},
        price: 130,
        description: 'Hot dog with extra toppings like cheese and jalapenos.',
      },
      {
        name: 'Chocolate Cheesecake',
        category: {name: 'Cake and Desserts'},
        price: 140,
        description: 'Rich and creamy chocolate cheesecake.',
      },
    ],
    rating: 4.7,
    deliveryCharge: 10,
    deliveryTime: 30,
  },
  {
    name: 'The Biryani House',
    description:
      'A premium place specializing in different types of biryanis and delicious pizzas.',
    items: [
      {
        name: 'Chicken Dum Biryani',
        category: {name: 'Biryani'},
        price: 280,
        description: 'Slow-cooked biryani with tender chicken pieces.',
      },
      {
        name: 'Paneer Biryani',
        category: {name: 'Biryani'},
        price: 240,
        description: 'Aromatic biryani made with cottage cheese.',
      },
      {
        name: 'Tandoori Chicken Pizza',
        category: {name: 'Pizza'},
        price: 210,
        description: 'Pizza with spicy tandoori chicken topping.',
      },
      {
        name: 'Veggie Delight Pizza',
        category: {name: 'Pizza'},
        price: 160,
        description: 'A pizza loaded with fresh vegetables and cheese.',
      },
      {
        name: 'Gulab Jamun Cake',
        category: {name: 'Cake and Desserts'},
        price: 100,
        description: 'A soft cake with gulab jamun flavor.',
      },
    ],
    rating: 4.5,
    deliveryCharge: 20,
    deliveryTime: 35,
  },
];
